version: '3'

services:
  app:
    build: MECAPRO
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/mecanica?serverTimezone=UTC  # 'db' es el nombre del servicio MySQL
      DB_USER_NAME: root
      DB_PASSWORD: 12345
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"  # Cambiado el puerto externo a 3307
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mecanica
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mysql_data: